"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import useToggle from "@/hooks/useToggle";
import MenuBarMobile from "@/components/MobilesMenu";
import Sidebar from "@/components/Dasbord";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Concatenate page title (if exists) to site title
  let titleConcat = "Responsive Sidebar Example";
  // if (pageTitle) titleConcat = pageTitle + " | " + titleConcat;

  // Mobile sidebar visibility state
  const [showSidebar, setShowSidebar] = useToggle(false);
  console.log("passed", showSidebar, setShowSidebar);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <MenuBarMobile setter={setShowSidebar} />
          <Sidebar show={showSidebar} setter={setShowSidebar} />

          {children}
        </div>
      </body>
    </html>
  );
}
