"use client";
import { LuUserCircle } from "react-icons/lu";
import { IoIosArrowForward } from "react-icons/io";
import { MdMenu } from "react-icons/md";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import useToggle from "@/hooks/useToggle";
import MenuBarMobile from "@/components/MobilesMenu";
import Sidebar from "@/components/Dasbord";
import { BsArrowRightShort, BsMenuApp } from "react-icons/bs";
import { FaHome } from "react-icons/fa";
import { UserIcon } from "lucide-react";
import { FiLogOut } from "react-icons/fi";
import { Button } from "@/components/ui/button";
import { IoMdHome } from "react-icons/io";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Concatenate page title (if exists) to site title
  let titleConcat = "Responsive Sidebar Example";
  // if (pageTitle) titleConcat = pageTitle + " | " + titleConcat;

  // Mobile sidebar visibility state
  const [showSidebar, setShowSidebar] = useToggle(false);
  console.log("passed", showSidebar, setShowSidebar);

  return (
    <html lang="en">
      <body className={inter.className + "bg-slate-100"}>
        <div className="flex">
          {/* <MenuBarMobile setter={setShowSidebar} /> */}
          <Sidebar show={showSidebar} setter={setShowSidebar} />
          <div className="flex-1 flex flex-col p-2 min-h-[100vh]">
            <header className="p-2 flex gap-2 flex-col border-s shadow-sm justify-center">
              <div className="text-sm flex justify-between items-center ">
                <div className="flex gap-1 items-center">
                  <button
                    onClick={setShowSidebar}
                    className="text-2xl !bg-none items-center flex mr-4 "
                  >
                    <MdMenu />
                  </button>
                  <IoMdHome></IoMdHome>
                  <div className="flex gap-1 items-center">
                    <IoIosArrowForward />
                    <span className="text-[.7rem] self-baseline">Profile</span>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <div className="flex gap-1 items-center">
                    <LuUserCircle></LuUserCircle>
                    <span className="text-[.7rem]">Profile</span>
                  </div>
                  <div className="flex gap-1 items-center">
                    <FiLogOut></FiLogOut>
                    <span className="text-[.7rem]">Logout</span>
                  </div>
                </div>
              </div>
              <div>
                <h2 className="text-2xl font-bold capitalize">Profile</h2>
              </div>
            </header>
            <main className="bg-slate-100 flex-1 ">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
